import type { Theme, ThemeId } from '../types/theme';

const THEMES: Record<ThemeId, Theme> = {
  zinc: {
    name: 'Graphite',
    dot: 'bg-zinc-500',
    accentHex: { light: '#ffffff', dark: '#18181b' },
    mermaid: {
      light: { fg: '#27272a', line: '#a1a1aa', border: '#e4e4e7', surface: '#ffffff', accent: '#18181b' },
      dark: { fg: '#f4f4f5', line: '#52525b', border: '#3f3f46', surface: '#18181b', accent: '#ffffff' },
    },
    ui: {
      light: {
        appBg: 'bg-zinc-100',
        appText: 'text-zinc-900',
        selection: 'selection:bg-zinc-300',
        panelBg: 'bg-white',
        panelBorder: 'border-zinc-200',
        iconBg: 'bg-zinc-900',
        iconText: 'text-white',
        resizeHandle: 'bg-zinc-200 hover:bg-zinc-400',
        previewBg: 'bg-zinc-50',
        previewHeaderBg: 'bg-white',
        previewTitle: 'text-zinc-500',
        btnSecondary: 'text-zinc-700 bg-zinc-100 hover:bg-zinc-200 border-zinc-200 hover:border-zinc-300',
        btnPrimary: 'text-white bg-zinc-900 hover:bg-zinc-800',
        editorLineNum: 'text-zinc-400 bg-zinc-50 border-zinc-200',
        editorText: 'text-zinc-800',
        editorBg: 'bg-white',
        dropdownBg: 'bg-white',
        dropdownBorder: 'border-zinc-200',
        dropdownHover: 'hover:bg-zinc-100',
        dropdownText: 'text-zinc-700',
        toggleBg: 'bg-zinc-200',
        toggleKnob: 'bg-white',
        tabActive: 'text-zinc-900',
        tabInactive: 'text-zinc-400',
        tabIndicator: 'bg-zinc-900',
        mobileToolbarBg: 'bg-white',
        mobileToolbarBorder: 'border-zinc-200',
      },
      dark: {
        appBg: 'bg-zinc-950',
        appText: 'text-zinc-100',
        selection: 'selection:bg-zinc-700',
        panelBg: 'bg-zinc-900',
        panelBorder: 'border-zinc-800',
        iconBg: 'bg-zinc-100',
        iconText: 'text-zinc-900',
        resizeHandle: 'bg-zinc-800 hover:bg-zinc-600',
        previewBg: 'bg-zinc-950',
        previewHeaderBg: 'bg-zinc-900',
        previewTitle: 'text-zinc-500',
        btnSecondary: 'text-zinc-300 bg-zinc-800 hover:bg-zinc-700 border-zinc-700 hover:border-zinc-600',
        btnPrimary: 'text-zinc-900 bg-zinc-100 hover:bg-white',
        editorLineNum: 'text-zinc-600 bg-zinc-900/50 border-zinc-800',
        editorText: 'text-zinc-200',
        editorBg: 'bg-zinc-900',
        dropdownBg: 'bg-zinc-800',
        dropdownBorder: 'border-zinc-700',
        dropdownHover: 'hover:bg-zinc-700',
        dropdownText: 'text-zinc-300',
        toggleBg: 'bg-zinc-700',
        toggleKnob: 'bg-zinc-200',
        tabActive: 'text-zinc-100',
        tabInactive: 'text-zinc-500',
        tabIndicator: 'bg-zinc-100',
        mobileToolbarBg: 'bg-zinc-900',
        mobileToolbarBorder: 'border-zinc-800',
      },
    },
  },
  blue: {
    name: 'Ocean',
    dot: 'bg-blue-500',
    accentHex: { light: '#ffffff', dark: '#0f172a' },
    mermaid: {
      light: { fg: '#1e3a8a', line: '#93c5fd', border: '#bfdbfe', surface: '#ffffff', accent: '#2563eb' },
      dark: { fg: '#eff6ff', line: '#3b82f6', border: '#1e40af', surface: '#0c1527', accent: '#60a5fa' },
    },
    ui: {
      light: {
        appBg: 'bg-slate-100',
        appText: 'text-slate-900',
        selection: 'selection:bg-blue-200',
        panelBg: 'bg-white',
        panelBorder: 'border-blue-200',
        iconBg: 'bg-blue-600',
        iconText: 'text-white',
        resizeHandle: 'bg-blue-200 hover:bg-blue-400',
        previewBg: 'bg-slate-50',
        previewHeaderBg: 'bg-white',
        previewTitle: 'text-blue-600',
        btnSecondary: 'text-blue-700 bg-blue-50 hover:bg-blue-100 border-blue-200 hover:border-blue-300',
        btnPrimary: 'text-white bg-blue-600 hover:bg-blue-700',
        editorLineNum: 'text-blue-400 bg-slate-50 border-blue-200',
        editorText: 'text-slate-800',
        editorBg: 'bg-white',
        dropdownBg: 'bg-white',
        dropdownBorder: 'border-blue-200',
        dropdownHover: 'hover:bg-blue-50',
        dropdownText: 'text-blue-700',
        toggleBg: 'bg-blue-200',
        toggleKnob: 'bg-white',
        tabActive: 'text-blue-600',
        tabInactive: 'text-slate-400',
        tabIndicator: 'bg-blue-600',
        mobileToolbarBg: 'bg-white',
        mobileToolbarBorder: 'border-blue-200',
      },
      dark: {
        appBg: 'bg-slate-950',
        appText: 'text-slate-100',
        selection: 'selection:bg-blue-900',
        panelBg: 'bg-slate-900',
        panelBorder: 'border-blue-900/60',
        iconBg: 'bg-blue-500',
        iconText: 'text-white',
        resizeHandle: 'bg-blue-900 hover:bg-blue-700',
        previewBg: 'bg-slate-950',
        previewHeaderBg: 'bg-slate-900',
        previewTitle: 'text-blue-400',
        btnSecondary: 'text-blue-300 bg-blue-900/40 hover:bg-blue-900/60 border-blue-800 hover:border-blue-700',
        btnPrimary: 'text-white bg-blue-600 hover:bg-blue-500',
        editorLineNum: 'text-blue-700 bg-slate-900/50 border-blue-900/60',
        editorText: 'text-slate-200',
        editorBg: 'bg-slate-900',
        dropdownBg: 'bg-slate-800',
        dropdownBorder: 'border-blue-800',
        dropdownHover: 'hover:bg-slate-700',
        dropdownText: 'text-blue-300',
        toggleBg: 'bg-blue-800',
        toggleKnob: 'bg-blue-200',
        tabActive: 'text-blue-400',
        tabInactive: 'text-slate-500',
        tabIndicator: 'bg-blue-400',
        mobileToolbarBg: 'bg-slate-900',
        mobileToolbarBorder: 'border-blue-900/60',
      },
    },
  },
  emerald: {
    name: 'Forest',
    dot: 'bg-emerald-500',
    accentHex: { light: '#ffffff', dark: '#1c1917' },
    mermaid: {
      light: { fg: '#064e3b', line: '#6ee7b7', border: '#a7f3d0', surface: '#ffffff', accent: '#059669' },
      dark: { fg: '#ecfdf5', line: '#10b981', border: '#065f46', surface: '#022c22', accent: '#34d399' },
    },
    ui: {
      light: {
        appBg: 'bg-stone-100',
        appText: 'text-stone-900',
        selection: 'selection:bg-emerald-200',
        panelBg: 'bg-white',
        panelBorder: 'border-emerald-200',
        iconBg: 'bg-emerald-600',
        iconText: 'text-white',
        resizeHandle: 'bg-emerald-200 hover:bg-emerald-400',
        previewBg: 'bg-stone-50',
        previewHeaderBg: 'bg-white',
        previewTitle: 'text-emerald-600',
        btnSecondary: 'text-emerald-700 bg-emerald-50 hover:bg-emerald-100 border-emerald-200 hover:border-emerald-300',
        btnPrimary: 'text-white bg-emerald-600 hover:bg-emerald-700',
        editorLineNum: 'text-emerald-400 bg-stone-50 border-emerald-200',
        editorText: 'text-stone-800',
        editorBg: 'bg-white',
        dropdownBg: 'bg-white',
        dropdownBorder: 'border-emerald-200',
        dropdownHover: 'hover:bg-emerald-50',
        dropdownText: 'text-emerald-700',
        toggleBg: 'bg-emerald-200',
        toggleKnob: 'bg-white',
        tabActive: 'text-emerald-600',
        tabInactive: 'text-stone-400',
        tabIndicator: 'bg-emerald-600',
        mobileToolbarBg: 'bg-white',
        mobileToolbarBorder: 'border-emerald-200',
      },
      dark: {
        appBg: 'bg-stone-950',
        appText: 'text-stone-100',
        selection: 'selection:bg-emerald-900',
        panelBg: 'bg-stone-900',
        panelBorder: 'border-emerald-900/60',
        iconBg: 'bg-emerald-500',
        iconText: 'text-white',
        resizeHandle: 'bg-emerald-900 hover:bg-emerald-700',
        previewBg: 'bg-stone-950',
        previewHeaderBg: 'bg-stone-900',
        previewTitle: 'text-emerald-400',
        btnSecondary: 'text-emerald-300 bg-emerald-900/40 hover:bg-emerald-900/60 border-emerald-800 hover:border-emerald-700',
        btnPrimary: 'text-white bg-emerald-600 hover:bg-emerald-500',
        editorLineNum: 'text-emerald-700 bg-stone-900/50 border-emerald-900/60',
        editorText: 'text-stone-200',
        editorBg: 'bg-stone-900',
        dropdownBg: 'bg-stone-800',
        dropdownBorder: 'border-emerald-800',
        dropdownHover: 'hover:bg-stone-700',
        dropdownText: 'text-emerald-300',
        toggleBg: 'bg-emerald-800',
        toggleKnob: 'bg-emerald-200',
        tabActive: 'text-emerald-400',
        tabInactive: 'text-stone-500',
        tabIndicator: 'bg-emerald-400',
        mobileToolbarBg: 'bg-stone-900',
        mobileToolbarBorder: 'border-emerald-900/60',
      },
    },
  },
  violet: {
    name: 'Lavender',
    dot: 'bg-violet-500',
    accentHex: { light: '#ffffff', dark: '#171717' },
    mermaid: {
      light: { fg: '#4c1d95', line: '#c4b5fd', border: '#ddd6fe', surface: '#ffffff', accent: '#7c3aed' },
      dark: { fg: '#f5f3ff', line: '#8b5cf6', border: '#4c1d95', surface: '#1a1530', accent: '#a78bfa' },
    },
    ui: {
      light: {
        appBg: 'bg-neutral-100',
        appText: 'text-neutral-900',
        selection: 'selection:bg-violet-200',
        panelBg: 'bg-white',
        panelBorder: 'border-violet-200',
        iconBg: 'bg-violet-600',
        iconText: 'text-white',
        resizeHandle: 'bg-violet-200 hover:bg-violet-400',
        previewBg: 'bg-neutral-50',
        previewHeaderBg: 'bg-white',
        previewTitle: 'text-violet-600',
        btnSecondary: 'text-violet-700 bg-violet-50 hover:bg-violet-100 border-violet-200 hover:border-violet-300',
        btnPrimary: 'text-white bg-violet-600 hover:bg-violet-700',
        editorLineNum: 'text-violet-400 bg-neutral-50 border-violet-200',
        editorText: 'text-neutral-800',
        editorBg: 'bg-white',
        dropdownBg: 'bg-white',
        dropdownBorder: 'border-violet-200',
        dropdownHover: 'hover:bg-violet-50',
        dropdownText: 'text-violet-700',
        toggleBg: 'bg-violet-200',
        toggleKnob: 'bg-white',
        tabActive: 'text-violet-600',
        tabInactive: 'text-neutral-400',
        tabIndicator: 'bg-violet-600',
        mobileToolbarBg: 'bg-white',
        mobileToolbarBorder: 'border-violet-200',
      },
      dark: {
        appBg: 'bg-neutral-950',
        appText: 'text-neutral-100',
        selection: 'selection:bg-violet-900',
        panelBg: 'bg-neutral-900',
        panelBorder: 'border-violet-900/60',
        iconBg: 'bg-violet-500',
        iconText: 'text-white',
        resizeHandle: 'bg-violet-900 hover:bg-violet-700',
        previewBg: 'bg-neutral-950',
        previewHeaderBg: 'bg-neutral-900',
        previewTitle: 'text-violet-400',
        btnSecondary: 'text-violet-300 bg-violet-900/40 hover:bg-violet-900/60 border-violet-800 hover:border-violet-700',
        btnPrimary: 'text-white bg-violet-600 hover:bg-violet-500',
        editorLineNum: 'text-violet-700 bg-neutral-900/50 border-violet-900/60',
        editorText: 'text-neutral-200',
        editorBg: 'bg-neutral-900',
        dropdownBg: 'bg-neutral-800',
        dropdownBorder: 'border-violet-800',
        dropdownHover: 'hover:bg-neutral-700',
        dropdownText: 'text-violet-300',
        toggleBg: 'bg-violet-800',
        toggleKnob: 'bg-violet-200',
        tabActive: 'text-violet-400',
        tabInactive: 'text-neutral-500',
        tabIndicator: 'bg-violet-400',
        mobileToolbarBg: 'bg-neutral-900',
        mobileToolbarBorder: 'border-violet-900/60',
      },
    },
  },
  orange: {
    name: 'Sunset',
    dot: 'bg-orange-500',
    accentHex: { light: '#ffffff', dark: '#1c1917' },
    mermaid: {
      light: { fg: '#7c2d12', line: '#fdba74', border: '#fed7aa', surface: '#ffffff', accent: '#ea580c' },
      dark: { fg: '#fff7ed', line: '#f97316', border: '#9a3412', surface: '#1c0f05', accent: '#fb923c' },
    },
    ui: {
      light: {
        appBg: 'bg-orange-50',
        appText: 'text-stone-900',
        selection: 'selection:bg-orange-200',
        panelBg: 'bg-white',
        panelBorder: 'border-orange-200',
        iconBg: 'bg-orange-600',
        iconText: 'text-white',
        resizeHandle: 'bg-orange-200 hover:bg-orange-400',
        previewBg: 'bg-orange-50/60',
        previewHeaderBg: 'bg-white',
        previewTitle: 'text-orange-600',
        btnSecondary: 'text-orange-700 bg-orange-50 hover:bg-orange-100 border-orange-200 hover:border-orange-300',
        btnPrimary: 'text-white bg-orange-600 hover:bg-orange-700',
        editorLineNum: 'text-orange-400 bg-orange-50/50 border-orange-200',
        editorText: 'text-stone-800',
        editorBg: 'bg-white',
        dropdownBg: 'bg-white',
        dropdownBorder: 'border-orange-200',
        dropdownHover: 'hover:bg-orange-50',
        dropdownText: 'text-orange-700',
        toggleBg: 'bg-orange-200',
        toggleKnob: 'bg-white',
        tabActive: 'text-orange-600',
        tabInactive: 'text-stone-400',
        tabIndicator: 'bg-orange-600',
        mobileToolbarBg: 'bg-white',
        mobileToolbarBorder: 'border-orange-200',
      },
      dark: {
        appBg: 'bg-stone-950',
        appText: 'text-stone-100',
        selection: 'selection:bg-orange-900',
        panelBg: 'bg-stone-900',
        panelBorder: 'border-orange-900/60',
        iconBg: 'bg-orange-500',
        iconText: 'text-white',
        resizeHandle: 'bg-orange-900 hover:bg-orange-700',
        previewBg: 'bg-stone-950',
        previewHeaderBg: 'bg-stone-900',
        previewTitle: 'text-orange-400',
        btnSecondary: 'text-orange-300 bg-orange-900/40 hover:bg-orange-900/60 border-orange-800 hover:border-orange-700',
        btnPrimary: 'text-white bg-orange-600 hover:bg-orange-500',
        editorLineNum: 'text-orange-700 bg-stone-900/50 border-orange-900/60',
        editorText: 'text-stone-200',
        editorBg: 'bg-stone-900',
        dropdownBg: 'bg-stone-800',
        dropdownBorder: 'border-orange-800',
        dropdownHover: 'hover:bg-stone-700',
        dropdownText: 'text-orange-300',
        toggleBg: 'bg-orange-800',
        toggleKnob: 'bg-orange-200',
        tabActive: 'text-orange-400',
        tabInactive: 'text-stone-500',
        tabIndicator: 'bg-orange-400',
        mobileToolbarBg: 'bg-stone-900',
        mobileToolbarBorder: 'border-orange-900/60',
      },
    },
  },
};

export default THEMES;
